version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_CODE_SERVER_IP
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"
      

  server:
    image: codercom/code-server:4.6.1@sha256:5ed6625453cadc093c782b515add2f186c9b9dc79e6391d6ba902a2f3d675c32
    restart: on-failure
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data:/home/coder
    environment:
      PASSWORD: $APP_PASSWORD
    networks:
      default:
        ipv4_address: $APP_CODE_SERVER_IP
