version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_MINECRAFT_SERVER_IP
      APP_PORT: $APP_MINECRAFT_SERVER_DYNMAP_PORT
  web:
    image: itzg/rcon
    restart: on-failure
    stop_grace_period: 1m
    environment:
      RWA_USERNAME: admin
      RWA_PASSWORD: admin
      RWA_ADMIN: "TRUE"
      # is referring to the hostname of 'mc' compose service below
      RWA_RCON_HOST: mc
      # needs to match the password configured for the container, which is 'minecraft' by default
      RWA_RCON_PASSWORD: minecraft
    ports:
      - ${APP_MINECRAFT_SERVER_RCON_WEBSOCKET_PORT}:4327
    networks:
      default:
        ipv4_address: ${APP_MINECRAFT_SERVER_RCON_IP}
  mc:
      image: itzg/minecraft-server
      restart: on-failure
      stop_grace_period: 1m
      ports:
        - ${APP_MINECRAFT_SERVER_GAME_PORT}:25565
      volumes:
        - ${APP_MINECRAFT_SERVER_DATA_DIR}:/data
      environment:
        EULA: "TRUE"
        TYPE: "PAPER"
        SPIGET_RESOURCES: "34315,274"
    networks:
      default:
        ipv4_address: ${APP_MINECRAFT_SERVER_IP}