version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_MINECRAFT_SERVER_IP
      APP_PORT: $APP_MINECRAFT_SERVER_DYNMAP_PORT
  mc:
      image: itzg/minecraft-server
      restart: on-failure
      stop_grace_period: 1m
      ports:
        - ${APP_MINECRAFT_SERVER_GAME_PORT}:25565
      volumes:
        - ${EXPORTS_APP_DIR}/data:/data
      environment:
        EULA: "TRUE"
        TYPE: "PAPER"
        SPIGET_RESOURCES: "34315, 274"
    networks:
      default:
        ipv4_address: $APP_MINECRAFT_SERVER_IP
