version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: $APP_NPROXYMANAGER_IP
      APP_PORT: $APP_NPROXYMANAGER_PORT
  web:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: on-failure
    stop_grace_period: 1m
    ports:
      # These ports are in format <host-port>:<container-port>
      - '$APP_NPROXYMANAGER_HTTP_PORT:80' # Public HTTP Port
      - '$APP_NPROXYMANAGER_HTTPS_PORT:443' # Public HTTPS Port
      - '$APP_NPROXYMANAGER_ADMIN_PORT:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    # Uncomment the next line if you uncomment anything in the section
    # environment:
      # Uncomment this if you want to change the location of 
      # the SQLite DB file within the container
      # DB_SQLITE_FILE: "/data/database.sqlite"

      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'

    volumes:
      - $APP_NPROXYMANAGER_DATA_DIR:/data
      - $APP_NPROXYMANAGER_LETSENCRYPT_DIR:/etc/letsencrypt